# Generated by Django 3.2.18 on 2023-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('team member', 'Team Member'), ('team head', 'Team Head')], default='team Members', max_length=50),
        ),
    ]
