# Generated by Django 3.2.9 on 2023-03-31 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20230330_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
