# Generated by Django 3.1.3 on 2023-04-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20230402_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
