# Generated by Django 3.2.9 on 2023-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('team member', 'Team Member'), ('team head', 'Team Head')], default='team Members', max_length=50),
        ),
    ]
